services:
  - type: web
    name: sorting-algorithms-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm ci && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: DATABASE_URL
        value: ./database.sqlite 